"""Motion IDs used by the physical CyberDog motion API."""

# Continuous servo motions (protocol/msg/MotionServoCmd)
SERVO_SLOW = 303
SERVO_MEDIUM = 308
SERVO_DEFAULT = SERVO_SLOW
SERVO_FRONT_BACK_JUMP = 301
SERVO_SMALL_JUMP = 302

# Result/service motions (protocol/srv/MotionResultCmd)
ACTION_EMERGENCY_STOP = 0
ACTION_LIE_DOWN_HIGH_DAMPING = 101
ACTION_RECOVERY_STAND = 111
ACTION_STRONG_STAND = 118
ACTION_TURN_LEFT_90 = 130
ACTION_TURN_RIGHT_90 = 131
ACTION_FORWARD_JUMP_60CM = 132
ACTION_LEFT_JUMP_20CM = 134
ACTION_RIGHT_JUMP_20CM = 135
